const abilityScores = require('../collections/abilityScores');
const alignments = require('../collections/alignments');
const backgrounds = require('../collections/backgrounds');
const classes = require('../collections/classes');
const conditions = require('../collections/conditions');
const damageTypes = require('../collections/damageTypes');
const equipment = require('../collections/equipment');
const equipmentCategories = require('../collections/equipmentCategories');
const feats = require('../collections/feats');
const features = require('../collections/features');
const languages = require('../collections/languages');
const levels = require('../collections/levels');
const magicItems = require('../collections/magicItems');
const magicSchools = require('../collections/magicSchools');
const monsters = require('../collections/monsters');
const proficiencies = require('../collections/proficiencies');
const races = require('../collections/races');
const rules = require('../collections/rules');
const ruleSections = require('../collections/ruleSections');
const skills = require('../collections/skills');
const spells = require('../collections/spells');
const subclasses = require('../collections/subclasses');
const subraces = require('../collections/subraces');
const traits = require('../collections/traits');
const weaponProperties = require('../collections/weaponProperties');

abilityScores.Request();
alignments.Request();
backgrounds.Request();
classes.Request();
conditions.Request();
damageTypes.Request();
equipment.Request();
equipmentCategories.Request();
feats.Request();
features.Request();
languages.Request();
levels.Request();
magicItems.Request();
magicSchools.Request();
monsters.Request();
proficiencies.Request();
races.Request();
rules.Request();
ruleSections.Request();
skills.Request();
spells.Request();
subclasses.Request();
subraces.Request();
traits.Request();
weaponProperties.Request();